// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package scryfall

import (
	"database/sql"
)

type Card struct {
	OracleID        string
	Name            string
	Layout          string
	PrintsSearchUri string
	RulingsUri      string
	AllParts        sql.NullString
	CardFaces       sql.NullString
	Cmc             float64
	ColorIdentity   string
	ColorIndicator  sql.NullString
	Colors          sql.NullString
	Defense         sql.NullString
	EdhrecRank      sql.NullInt64
	GameChanger     sql.NullBool
	HandModifier    sql.NullString
	Keywords        string
	Legalities      string
	LifeModifier    sql.NullString
	Loyalty         sql.NullString
	ManaCost        sql.NullString
	OracleText      sql.NullString
	PennyRank       sql.NullInt64
	Power           sql.NullString
	ProducedMana    sql.NullString
	Reserved        bool
	Toughness       sql.NullString
	TypeLine        string
}

type Printing struct {
	ID                string
	OracleID          string
	ArenaID           sql.NullInt64
	Lang              string
	MtgoID            sql.NullInt64
	MtgoFoilID        sql.NullInt64
	MultiverseIds     sql.NullString
	TcgplayerID       sql.NullInt64
	TcgplayerEtchedID sql.NullInt64
	CardmarketID      sql.NullInt64
	Object            string
	ScryfallUri       string
	Uri               string
	Artist            sql.NullString
	ArtistIds         sql.NullString
	AttractionLights  sql.NullString
	Booster           bool
	BorderColor       string
	CardBackID        string
	CollectorNumber   string
	ContentWarning    sql.NullBool
	Digital           bool
	Finishes          string
	FlavorName        sql.NullString
	FlavorText        sql.NullString
	Foil              bool
	Nonfoil           bool
	FrameEffects      sql.NullString
	Frame             string
	FullArt           bool
	Games             string
	HighresImage      bool
	IllustrationID    sql.NullString
	ImageStatus       string
	ImageUris         sql.NullString
	Oversized         bool
	Prices            string
	PrintedName       sql.NullString
	PrintedText       sql.NullString
	PrintedTypeLine   sql.NullString
	Promo             bool
	PromoTypes        sql.NullString
	PurchaseUris      sql.NullString
	Rarity            string
	RelatedUris       string
	ReleasedAt        string
	Reprint           bool
	ScryfallSetUri    string
	SetName           string
	SetSearchUri      string
	SetType           string
	SetUri            string
	Set               string
	SetID             string
	StorySpotlight    bool
	Textless          bool
	Variation         bool
	VariationOf       sql.NullString
	SecurityStamp     sql.NullString
	Watermark         sql.NullString
	Preview           sql.NullString
}
