-- Get all cards
-- name: GetCards :many
SELECT * FROM cards;

-- Insert or update a card
-- name: UpsertCard :exec
INSERT INTO cards (
    arena_id, id, lang, mtgo_id, mtgo_foil_id, multiverse_ids,
    tcgplayer_id, tcgplayer_etched_id, cardmarket_id, object, layout, oracle_id,
    prints_search_uri, rulings_uri, scryfall_uri, uri, all_parts, card_faces,
    cmc, color_identity, color_indicator, colors, defense, edhrec_rank,
    game_changer, hand_modifier, keywords, legalities, life_modifier, loyalty,
    mana_cost, name, oracle_text, penny_rank, power, produced_mana, reserved,
    toughness, type_line, artist, artist_ids, attraction_lights, booster,
    border_color, card_back_id, collector_number, content_warning, digital,
    finishes, flavor_name, flavor_text, frame_effects, frame, full_art, games,
    highres_image, illustration_id, image_status, image_uris, oversized, prices,
    printed_name, printed_text, printed_type_line, promo, promo_types,
    purchase_uris, rarity, related_uris, released_at, reprint, scryfall_set_uri,
    set_name, set_search_uri, set_type, set_uri, set_code, set_id,
    story_spotlight, textless, variation, variation_of, security_stamp,
    watermark, preview
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(id) DO UPDATE SET
    arena_id = excluded.arena_id,
    lang = excluded.lang,
    mtgo_id = excluded.mtgo_id,
    mtgo_foil_id = excluded.mtgo_foil_id,
    multiverse_ids = excluded.multiverse_ids,
    tcgplayer_id = excluded.tcgplayer_id,
    tcgplayer_etched_id = excluded.tcgplayer_etched_id,
    cardmarket_id = excluded.cardmarket_id,
    object = excluded.object,
    layout = excluded.layout,
    oracle_id = excluded.oracle_id,
    prints_search_uri = excluded.prints_search_uri,
    rulings_uri = excluded.rulings_uri,
    scryfall_uri = excluded.scryfall_uri,
    uri = excluded.uri,
    all_parts = excluded.all_parts,
    card_faces = excluded.card_faces,
    cmc = excluded.cmc,
    color_identity = excluded.color_identity,
    color_indicator = excluded.color_indicator,
    colors = excluded.colors,
    defense = excluded.defense,
    edhrec_rank = excluded.edhrec_rank,
    game_changer = excluded.game_changer,
    hand_modifier = excluded.hand_modifier,
    keywords = excluded.keywords,
    legalities = excluded.legalities,
    life_modifier = excluded.life_modifier,
    loyalty = excluded.loyalty,
    mana_cost = excluded.mana_cost,
    name = excluded.name,
    oracle_text = excluded.oracle_text,
    penny_rank = excluded.penny_rank,
    power = excluded.power,
    produced_mana = excluded.produced_mana,
    reserved = excluded.reserved,
    toughness = excluded.toughness,
    type_line = excluded.type_line,
    artist = excluded.artist,
    artist_ids = excluded.artist_ids,
    attraction_lights = excluded.attraction_lights,
    booster = excluded.booster,
    border_color = excluded.border_color,
    card_back_id = excluded.card_back_id,
    collector_number = excluded.collector_number,
    content_warning = excluded.content_warning,
    digital = excluded.digital,
    finishes = excluded.finishes,
    flavor_name = excluded.flavor_name,
    flavor_text = excluded.flavor_text,
    frame_effects = excluded.frame_effects,
    frame = excluded.frame,
    full_art = excluded.full_art,
    games = excluded.games,
    highres_image = excluded.highres_image,
    illustration_id = excluded.illustration_id,
    image_status = excluded.image_status,
    image_uris = excluded.image_uris,
    oversized = excluded.oversized,
    prices = excluded.prices,
    printed_name = excluded.printed_name,
    printed_text = excluded.printed_text,
    printed_type_line = excluded.printed_type_line,
    promo = excluded.promo,
    promo_types = excluded.promo_types,
    purchase_uris = excluded.purchase_uris,
    rarity = excluded.rarity,
    related_uris = excluded.related_uris,
    released_at = excluded.released_at,
    reprint = excluded.reprint,
    scryfall_set_uri = excluded.scryfall_set_uri,
    set_name = excluded.set_name,
    set_search_uri = excluded.set_search_uri,
    set_type = excluded.set_type,
    set_uri = excluded.set_uri,
    set_code = excluded.set_code,
    set_id = excluded.set_id,
    story_spotlight = excluded.story_spotlight,
    textless = excluded.textless,
    variation = excluded.variation,
    variation_of = excluded.variation_of,
    security_stamp = excluded.security_stamp,
    watermark = excluded.watermark,
    preview = excluded.preview;